pcgf_smiliecreator_get_creator:
    path: /pcgf/smiliecreator
    defaults: { _controller: pcgf.smiliecreator.controller:get_smilie_creator }
pcgf_smiliecreator_get_shield:
    path: /pcgf/getsmilieshield
    defaults: { _controller: pcgf.smiliecreator.controller:get_shield }